package biblioteca.modulovisitas;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.FieldEvents.FocusEvent;
import com.vaadin.event.FieldEvents.FocusListener;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

import biblioteca.modulovisitas.validadores.IsApellido;
import biblioteca.modulovisitas.validadores.IsCarne;
import biblioteca.modulovisitas.validadores.IsCedula;
import biblioteca.modulovisitas.validadores.IsEmail;
import biblioteca.modulovisitas.validadores.IsFecha;
import biblioteca.modulovisitas.validadores.IsInstitucion;
import biblioteca.modulovisitas.validadores.IsNombre;
import biblioteca.modulovisitas.validadores.IsTelefono;

public class formularioEditarConsulta extends CustomComponent implements View
{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private CheckBox checkBoxOTRAS;

	@AutoGenerated
	private CheckBox checkBoxDIALNET;

	@AutoGenerated
	private CheckBox checkBoxSCIJ;

	@AutoGenerated
	private CheckBox checkBoxOPAC;

	@AutoGenerated
	private CheckBox checkBoxMASTERLEX;

	@AutoGenerated
	private CheckBox checkBoxCIJUL;

	@AutoGenerated
	private CheckBox checkBoxCRIJA;

	@AutoGenerated
	private TextField inputTema;

	@AutoGenerated
	private Label labelBasesDatos;

	@AutoGenerated
	private Label labelTema;

	@AutoGenerated
	private Label labelFechaEntrega;

	@AutoGenerated
	private TextField inputFechaEntrega;

	@AutoGenerated
	private TextField inputObservaciones;

	@AutoGenerated
	private Label labelObservaciones;

	@AutoGenerated
	private Label labelSoy;

	@AutoGenerated
	private Button botonGuardar;

	@AutoGenerated
	private Label labelFechaHora;

	@AutoGenerated
	private Label labelEMail;

	@AutoGenerated
	private TextField inputEmail;

	@AutoGenerated
	private TextField inputInstitucion;

	@AutoGenerated
	private Label labelInstitucion;

	@AutoGenerated
	private ComboBox inputTipoConsulta;

	@AutoGenerated
	private ComboBox inputSoy;

	@AutoGenerated
	private TextField inputTelefono;

	@AutoGenerated
	private TextField inputCarne;

	@AutoGenerated
	private Label labelTipoConsulta;

	@AutoGenerated
	private Label labelCarne;

	@AutoGenerated
	private TextField inputCedula;

	@AutoGenerated
	private Label labelCedula;

	@AutoGenerated
	private TextField inputApellidos;

	@AutoGenerated
	private Label labelTelefono;

	@AutoGenerated
	private Label labelApellidos;

	@AutoGenerated
	private Label labelNombre;

	@AutoGenerated
	private TextField inputNombre;

	@AutoGenerated
	private Label labelTitulo;

	public static final long serialVersionUID = 1202;
	
	private String timeStamp;

	private final DBConnector dbc;
	
	private String IDConsulta;
	
	public static final String EDITVIEW = "edit";
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public formularioEditarConsulta(String idConsulta, String nombre, String apellidos,
	String cedula, String carne, String email, String telefono, String institucion, String tipoUsuario, String tema,
	String tipoConsulta, String observaciones, String basesDatos) 
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		dbc = new DBConnector("localhost","Mutaclotos","we105769");

		timeStamp = new SimpleDateFormat("dd/MM/YYYY HH:mm").format(Calendar.getInstance().getTime());
		labelFechaHora.setValue(timeStamp);
		
		IDConsulta = idConsulta;
		
		//FocusListener para verificar validez de campo modificado
		FocusListener fl = new FocusListener(){
			@Override
			public void focus(FocusEvent event) {
				inputFechaEntrega.isValid();
			}
		};
		
		
		inputFechaEntrega.addFocusListener(fl);
		botonGuardar.addFocusListener(fl);
		
		//Se insertan los valores de la fila de la tabla de consultas en su campo respectivo
		inputNombre.setValue(nombre);
		inputApellidos.setValue(apellidos);
		inputCarne.setValue(carne);
		inputCedula.setValue(cedula);
		inputEmail.setValue(email);
		inputTelefono.setValue(telefono);
		inputFechaEntrega.setValue("");
		inputInstitucion.setValue(institucion);
		inputObservaciones.setValue(observaciones);
		inputTema.setValue(tema);
		
		inputSoy.setContainerDataSource(Contenedor.obtenerContenedorTipoUsuario("tipoSoy"));
		inputTipoConsulta.setContainerDataSource(Contenedor.obtenerContenedorTipoConsulta("tipoConsulta"));
		
		inputSoy.select(tipoUsuario);
		inputTipoConsulta.select(tipoConsulta);
		
		String[] bases = setSelectedDataBases(basesDatos);
		for(String base : bases)
		{
			switch(base)
			{
				case "CRIJA":
					checkBoxCRIJA.setValue(true);
					break;
				case "CIJUL":
					checkBoxCIJUL.setValue(true);
					break;
				case "MASTERLEX":
					checkBoxMASTERLEX.setValue(true);
					break;
				case "OPAC":
					checkBoxOPAC.setValue(true);
					break;
				case "SCIJ":
					checkBoxSCIJ.setValue(true);
					break;
				case "DIALNET":
					checkBoxDIALNET.setValue(true);
					break;
				case "OTRAS":
					checkBoxOTRAS.setValue(true);
					break;
				
			}
		}
		
		inputNombre.setReadOnly(true);
		inputApellidos.setReadOnly(true);
		inputCarne.setReadOnly(true);
		inputCedula.setReadOnly(true);
		inputEmail.setReadOnly(true);
		inputTelefono.setReadOnly(true);
		inputInstitucion.setReadOnly(true);
		inputSoy.setReadOnly(true);
		
		
		botonGuardar.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
			{
				
				inputFechaEntrega.addValidator(new IsFecha());	
				
				String fechaEntrega;
				String tipoConsulta;
				String tema;
				String observaciones;
				
				if(inputFechaEntrega.getValue().equals(""))
				{
					fechaEntrega = null;
				}
				else
				{
					fechaEntrega = (new SimpleDateFormat("YYYY-MM-dd ").format(Calendar.getInstance().getTime())) + inputFechaEntrega.getValue();
				}
				
				tipoConsulta = inputTipoConsulta.getValue().toString();
				tema = inputTema.getValue();
				observaciones = inputObservaciones.getValue();
				
				if(inputFechaEntrega.isValid())
				{
					
					try{
						dbc.update("Consulta","tema='"+tema+"', fechaEntrega='"+fechaEntrega+"', observaciones='"+observaciones+"', tipo='"+tipoConsulta+"'","id='"+IDConsulta+"'");
					}catch(Exception sqe){
					}
					
						//System.out.println("Consulta modificada: " + Integer.toString(idConsulta) +" " + tema +" " + fechaEntrega+" " + observaciones+" " + cedula+" " + tipoConsulta);
						if(checkBoxCRIJA.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(1) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(1),IDConsulta);
						}
						if(checkBoxCIJUL.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(2) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(2),IDConsulta);
						}
						if(checkBoxMASTERLEX.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(3) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(3),IDConsulta);
						}
						if(checkBoxOPAC.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(4) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(4),IDConsulta);
						}
						if(checkBoxSCIJ.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(5) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(5),IDConsulta);
						}
						if(checkBoxDIALNET.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(6) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(6),IDConsulta);
						}
						if(checkBoxOTRAS.getValue())
						{
							//System.out.println("Id Base de datos: " + Integer.toString(7) + " Id Consulta: " + Integer.toString(idConsulta));
							dbc.insert("Consultabase",Integer.toString(7),IDConsulta);
						}
					
						UI.getCurrent().setContent(new formularioConsultaNoCompletada());
				}
			}
		});
	}
	
	@Override
    public void enter(ViewChangeEvent event) {
        Notification.show("Formulario de editar consulta.");
    }
	

	private String[] setSelectedDataBases(String basesDatos)
	{
		String[] bases = basesDatos.split(",");
		
		return bases;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("623px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("623px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("EDITAR CONSULTA");
		mainLayout.addComponent(labelTitulo, "top:0.0px;left:290.0px;");
		
		// inputNombre
		inputNombre = new TextField();
		inputNombre.setImmediate(false);
		inputNombre.setWidth("-1px");
		inputNombre.setHeight("-1px");
		mainLayout.addComponent(inputNombre, "top:116.0px;left:120.0px;");
		
		// labelNombre
		labelNombre = new Label();
		labelNombre.setImmediate(false);
		labelNombre.setWidth("-1px");
		labelNombre.setHeight("-1px");
		labelNombre.setValue("Nombre:");
		mainLayout.addComponent(labelNombre, "top:120.0px;left:34.0px;");
		
		// labelApellidos
		labelApellidos = new Label();
		labelApellidos.setImmediate(false);
		labelApellidos.setWidth("-1px");
		labelApellidos.setHeight("-1px");
		labelApellidos.setValue("Apellidos:");
		mainLayout.addComponent(labelApellidos, "top:120.0px;left:330.0px;");
		
		// labelTelefono
		labelTelefono = new Label();
		labelTelefono.setImmediate(false);
		labelTelefono.setWidth("-1px");
		labelTelefono.setHeight("-1px");
		labelTelefono.setValue("Telefono:");
		mainLayout.addComponent(labelTelefono, "top:242.0px;left:330.0px;");
		
		// inputApellidos
		inputApellidos = new TextField();
		inputApellidos.setImmediate(false);
		inputApellidos.setWidth("-1px");
		inputApellidos.setHeight("-1px");
		mainLayout.addComponent(inputApellidos, "top:116.0px;left:419.0px;");
		
		// labelCedula
		labelCedula = new Label();
		labelCedula.setImmediate(false);
		labelCedula.setWidth("-1px");
		labelCedula.setHeight("-1px");
		labelCedula.setValue("Cédula:");
		mainLayout.addComponent(labelCedula, "top:60.0px;left:39.0px;");
		
		// inputCedula
		inputCedula = new TextField();
		inputCedula.setImmediate(false);
		inputCedula.setWidth("-1px");
		inputCedula.setHeight("-1px");
		mainLayout.addComponent(inputCedula, "top:60.0px;left:120.0px;");
		
		// labelCarne
		labelCarne = new Label();
		labelCarne.setImmediate(false);
		labelCarne.setWidth("-1px");
		labelCarne.setHeight("-1px");
		labelCarne.setValue("Carné:");
		mainLayout.addComponent(labelCarne, "top:60.0px;left:344.0px;");
		
		// labelTipoConsulta
		labelTipoConsulta = new Label();
		labelTipoConsulta.setImmediate(false);
		labelTipoConsulta.setWidth("-1px");
		labelTipoConsulta.setHeight("-1px");
		labelTipoConsulta.setValue("Tipo de consulta:");
		mainLayout.addComponent(labelTipoConsulta, "top:517.0px;left:323.0px;");
		
		// inputCarne
		inputCarne = new TextField();
		inputCarne.setImmediate(false);
		inputCarne.setWidth("-1px");
		inputCarne.setHeight("-1px");
		mainLayout.addComponent(inputCarne, "top:60.0px;left:419.0px;");
		
		// inputTelefono
		inputTelefono = new TextField();
		inputTelefono.setImmediate(false);
		inputTelefono.setWidth("-1px");
		inputTelefono.setHeight("-1px");
		mainLayout.addComponent(inputTelefono, "top:236.0px;left:420.0px;");
		
		// inputSoy
		inputSoy = new ComboBox();
		inputSoy.setImmediate(false);
		inputSoy.setWidth("141px");
		inputSoy.setHeight("-1px");
		mainLayout.addComponent(inputSoy, "top:240.0px;left:120.0px;");
		
		// inputTipoConsulta
		inputTipoConsulta = new ComboBox();
		inputTipoConsulta.setImmediate(false);
		inputTipoConsulta.setWidth("141px");
		inputTipoConsulta.setHeight("-1px");
		mainLayout.addComponent(inputTipoConsulta, "top:517.0px;left:460.0px;");
		
		// labelInstitucion
		labelInstitucion = new Label();
		labelInstitucion.setImmediate(false);
		labelInstitucion.setWidth("-1px");
		labelInstitucion.setHeight("-1px");
		labelInstitucion.setValue("Institucion:");
		mainLayout.addComponent(labelInstitucion, "top:180.0px;left:323.0px;");
		
		// inputInstitucion
		inputInstitucion = new TextField();
		inputInstitucion.setImmediate(false);
		inputInstitucion.setWidth("-1px");
		inputInstitucion.setHeight("-1px");
		mainLayout.addComponent(inputInstitucion, "top:176.0px;left:419.0px;");
		
		// inputEmail
		inputEmail = new TextField();
		inputEmail.setImmediate(false);
		inputEmail.setWidth("-1px");
		inputEmail.setHeight("-1px");
		mainLayout.addComponent(inputEmail, "top:176.0px;left:120.0px;");
		
		// labelEMail
		labelEMail = new Label();
		labelEMail.setImmediate(false);
		labelEMail.setWidth("-1px");
		labelEMail.setHeight("-1px");
		labelEMail.setValue("E-mail:");
		mainLayout.addComponent(labelEMail, "top:180.0px;left:43.0px;");
		
		// labelFechaHora
		labelFechaHora = new Label();
		labelFechaHora.setImmediate(false);
		labelFechaHora.setWidth("-1px");
		labelFechaHora.setHeight("-1px");
		labelFechaHora.setValue("1/6/2016  14:21");
		mainLayout.addComponent(labelFechaHora, "top:20.0px;left:480.0px;");
		
		// botonGuardar
		botonGuardar = new Button();
		botonGuardar.setCaption("EDITAR CONSULTA");
		botonGuardar.setImmediate(true);
		botonGuardar.setWidth("240px");
		botonGuardar.setHeight("40px");
		mainLayout.addComponent(botonGuardar, "top:587.0px;left:240.0px;");
		
		// labelSoy
		labelSoy = new Label();
		labelSoy.setImmediate(false);
		labelSoy.setWidth("-1px");
		labelSoy.setHeight("-1px");
		labelSoy.setValue("Tipo Usuario:");
		mainLayout.addComponent(labelSoy, "top:242.0px;left:9.0px;");
		
		// labelObservaciones
		labelObservaciones = new Label();
		labelObservaciones.setImmediate(false);
		labelObservaciones.setWidth("-1px");
		labelObservaciones.setHeight("-1px");
		labelObservaciones.setValue("Observaciones:");
		mainLayout.addComponent(labelObservaciones, "top:437.0px;left:0.0px;");
		
		// inputObservaciones
		inputObservaciones = new TextField();
		inputObservaciones.setImmediate(false);
		inputObservaciones.setWidth("480px");
		inputObservaciones.setHeight("-1px");
		mainLayout.addComponent(inputObservaciones, "top:437.0px;left:120.0px;");
		
		// inputFechaEntrega
		inputFechaEntrega = new TextField();
		inputFechaEntrega.setImmediate(false);
		inputFechaEntrega.setWidth("-1px");
		inputFechaEntrega.setHeight("-1px");
		mainLayout.addComponent(inputFechaEntrega, "top:517.0px;left:120.0px;");
		
		// labelFechaEntrega
		labelFechaEntrega = new Label();
		labelFechaEntrega.setImmediate(false);
		labelFechaEntrega.setWidth("-1px");
		labelFechaEntrega.setHeight("-1px");
		labelFechaEntrega.setValue("Fecha entrega:");
		mainLayout.addComponent(labelFechaEntrega, "top:517.0px;left:2.0px;");
		
		// labelTema
		labelTema = new Label();
		labelTema.setImmediate(false);
		labelTema.setWidth("-1px");
		labelTema.setHeight("-1px");
		labelTema.setValue("Tema:");
		mainLayout.addComponent(labelTema, "top:300.0px;left:46.0px;");
		
		// labelBasesDatos
		labelBasesDatos = new Label();
		labelBasesDatos.setImmediate(false);
		labelBasesDatos.setWidth("-1px");
		labelBasesDatos.setHeight("-1px");
		labelBasesDatos.setValue("Bases de Datos consultadas:");
		mainLayout.addComponent(labelBasesDatos, "top:342.0px;left:265.0px;");
		
		// inputTema
		inputTema = new TextField();
		inputTema.setImmediate(false);
		inputTema.setWidth("480px");
		inputTema.setHeight("-1px");
		mainLayout.addComponent(inputTema, "top:300.0px;left:120.0px;");
		
		// checkBoxCRIJA
		checkBoxCRIJA = new CheckBox();
		checkBoxCRIJA.setCaption("CRIJA");
		checkBoxCRIJA.setImmediate(false);
		checkBoxCRIJA.setWidth("-1px");
		checkBoxCRIJA.setHeight("-1px");
		mainLayout.addComponent(checkBoxCRIJA, "top:376.0px;left:43.0px;");
		
		// checkBoxCIJUL
		checkBoxCIJUL = new CheckBox();
		checkBoxCIJUL.setCaption("CIJUL");
		checkBoxCIJUL.setImmediate(false);
		checkBoxCIJUL.setWidth("-1px");
		checkBoxCIJUL.setHeight("-1px");
		mainLayout.addComponent(checkBoxCIJUL, "top:376.0px;left:117.0px;");
		
		// checkBoxMASTERLEX
		checkBoxMASTERLEX = new CheckBox();
		checkBoxMASTERLEX.setCaption("MASTERLEX");
		checkBoxMASTERLEX.setImmediate(false);
		checkBoxMASTERLEX.setWidth("-1px");
		checkBoxMASTERLEX.setHeight("-1px");
		mainLayout.addComponent(checkBoxMASTERLEX, "top:376.0px;left:200.0px;");
		
		// checkBoxOPAC
		checkBoxOPAC = new CheckBox();
		checkBoxOPAC.setCaption("OPAC");
		checkBoxOPAC.setImmediate(false);
		checkBoxOPAC.setWidth("-1px");
		checkBoxOPAC.setHeight("-1px");
		mainLayout.addComponent(checkBoxOPAC, "top:376.0px;left:330.0px;");
		
		// checkBoxSCIJ
		checkBoxSCIJ = new CheckBox();
		checkBoxSCIJ.setCaption("SCIJ");
		checkBoxSCIJ.setImmediate(false);
		checkBoxSCIJ.setWidth("-1px");
		checkBoxSCIJ.setHeight("-1px");
		mainLayout.addComponent(checkBoxSCIJ, "top:376.0px;left:420.0px;");
		
		// checkBoxDIALNET
		checkBoxDIALNET = new CheckBox();
		checkBoxDIALNET.setCaption("DIALNET");
		checkBoxDIALNET.setImmediate(false);
		checkBoxDIALNET.setWidth("-1px");
		checkBoxDIALNET.setHeight("-1px");
		mainLayout.addComponent(checkBoxDIALNET, "top:376.0px;left:500.0px;");
		
		// checkBoxOTRAS
		checkBoxOTRAS = new CheckBox();
		checkBoxOTRAS.setCaption("OTRAS");
		checkBoxOTRAS.setImmediate(false);
		checkBoxOTRAS.setWidth("-1px");
		checkBoxOTRAS.setHeight("-1px");
		mainLayout.addComponent(checkBoxOTRAS, "top:376.0px;left:600.0px;");
		
		return mainLayout;
	}

}
