package biblioteca.modulovisitas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;

public class formularioentrada extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_11;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private TextField textField_8;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private TextField textField_7;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private TextField textField_6;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private TextField textField_5;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private TextField textField_4;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private TextField textField_3;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private Label label_3;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public formularioentrada() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("460px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("460px");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("CONTROl VISITAS");
		mainLayout.addComponent(label_3, "top:20.0px;left:256.0px;");
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		mainLayout.addComponent(textField_2, "top:100.0px;left:120.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Nombre:");
		mainLayout.addComponent(label_4, "top:100.0px;left:54.0px;");
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Apellidos:");
		mainLayout.addComponent(label_5, "top:100.0px;left:289.0px;");
		
		// textField_3
		textField_3 = new TextField();
		textField_3.setImmediate(false);
		textField_3.setWidth("-1px");
		textField_3.setHeight("-1px");
		mainLayout.addComponent(textField_3, "top:100.0px;left:359.0px;");
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Cedula:");
		mainLayout.addComponent(label_6, "top:140.0px;left:59.0px;");
		
		// textField_4
		textField_4 = new TextField();
		textField_4.setImmediate(false);
		textField_4.setWidth("-1px");
		textField_4.setHeight("-1px");
		mainLayout.addComponent(textField_4, "top:140.0px;left:120.0px;");
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Carne:");
		mainLayout.addComponent(label_7, "top:140.0px;left:305.0px;");
		
		// textField_5
		textField_5 = new TextField();
		textField_5.setImmediate(false);
		textField_5.setWidth("-1px");
		textField_5.setHeight("-1px");
		mainLayout.addComponent(textField_5, "top:140.0px;left:359.0px;");
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("141px");
		comboBox_1.setHeight("-1px");
		mainLayout.addComponent(comboBox_1, "top:176.0px;left:120.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Soy: ");
		mainLayout.addComponent(label_1, "top:180.0px;left:76.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Institucion:");
		mainLayout.addComponent(label_2, "top:180.0px;left:284.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		mainLayout.addComponent(textField_1, "top:176.0px;left:359.0px;");
		
		// textField_6
		textField_6 = new TextField();
		textField_6.setImmediate(false);
		textField_6.setWidth("-1px");
		textField_6.setHeight("-1px");
		mainLayout.addComponent(textField_6, "top:220.0px;left:120.0px;");
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("E-mail:");
		mainLayout.addComponent(label_8, "top:220.0px;left:63.0px;");
		
		// panel_2
		panel_2 = buildPanel_2();
		mainLayout.addComponent(panel_2, "top:260.0px;left:20.0px;");
		
		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("1/6/2016  14:21");
		mainLayout.addComponent(label_11, "top:20.0px;left:480.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setWidth("540px");
		panel_2.setHeight("140px");
		
		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		panel_2.setContent(absoluteLayout_3);
		
		return panel_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("121.43%");
		absoluteLayout_3.setHeight("218.52%");
		
		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("Hora entrada:");
		absoluteLayout_3.addComponent(label_9, "top:19.0px;left:33.0px;");
		
		// textField_7
		textField_7 = new TextField();
		textField_7.setImmediate(false);
		textField_7.setWidth("-1px");
		textField_7.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_7, "top:19.0px;left:106.0px;");
		
		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("-1px");
		label_10.setHeight("-1px");
		label_10.setValue("Hora salida:");
		absoluteLayout_3.addComponent(label_10, "top:19.0px;left:268.0px;");
		
		// textField_8
		textField_8 = new TextField();
		textField_8.setImmediate(false);
		textField_8.setWidth("-1px");
		textField_8.setHeight("-1px");
		absoluteLayout_3.addComponent(textField_8, "top:19.0px;left:341.0px;");
		
		return absoluteLayout_3;
	}

}
