package biblioteca.modulovisitas;

import java.sql.ResultSet;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class formularioHistorialPrestamos extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table tablaHistorial;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Label labelBiblioteca;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private final DBConnector dbc;
	
	private MyUI ui;
	
	public formularioHistorialPrestamos() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		dbc = new DBConnector("localhost","moises","315600");
		ui = new MyUI();
		

		// TODO add user code here
		//mostrar del documento: nombre fecha de retiro, signatura, autor, tipo, anio, editorial
		tablaHistorial.addContainerProperty("   fecha  ", String.class, null);
		tablaHistorial.addContainerProperty("nombre de libro", String.class, null);
		tablaHistorial.addContainerProperty("autor", String.class, null);
		tablaHistorial.addContainerProperty("asignatura ", String.class, null);
		tablaHistorial.addContainerProperty("tipo", String.class, null);
		tablaHistorial.addContainerProperty("año ", String.class, null);
		tablaHistorial.addContainerProperty("editorial", String.class, null);
		int i=0;
		
		//añadir condicion de la cedula del usuario actual"
		ResultSet rs = dbc.query("select p.fechaEntrega, d.titulo , a.nombre , d.signatura , d.tipoDocumento, d.anio, d.editorial from Documento d, prestamo p, usuario u,documentoautor da,autor a	where p.usuario=u.cedula and p.documento= d.signatura and da.documento= d.signatura and da.autor = a.id	group by p.Documento;" );
		
		/*	select p.fechaEntrega, d.titulo , a.nombre , d.signatura , d.tipoDocumento, d.anio, d.editorial
		from Documento d, prestamo p, usuario u,documentoautor da,autor a 
		where p.usuario=u.cedula
		and p.documento= d.signatura
        and da.documento= d.signatura
        and da.autor = a.id
		group by p.Documento
		
		
		
		*/
		try{	
			//TODO: datasource de resultSet, tableQuery	
				while(rs.next())
				{
					Integer itemId = new Integer(i);
					
					
					String fechaDevolucion = rs.getString("fechaEntrega");
					String nombreA = rs.getString("nombre");
					String titulo = rs.getString("titulo"); 
					String signatura = rs.getString("signatura");
					String tipoDocumento = rs.getString("tipoDocumento"); 
					String anio = rs.getString("anio");
					String editorial = rs.getString("editorial"); 

					tablaHistorial.addItem(new Object[]{fechaDevolucion,titulo,nombreA,signatura,tipoDocumento,anio,editorial}, itemId);
					
					i++;
					System.out.println(titulo);
					System.out.println(fechaDevolucion);
				}
						
			
			}catch(Exception sqe){
				System.out.println("faillllll");
			}
			

			tablaHistorial.setPageLength(tablaHistorial.size());
		
		
		
		
		
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelBiblioteca
		labelBiblioteca = new Label();
		labelBiblioteca.setImmediate(false);
		labelBiblioteca.setWidth("-1px");
		labelBiblioteca.setHeight("-1px");
		labelBiblioteca.setValue("Biblioteca Francisco Echeverria Garcìa");
		mainLayout.addComponent(labelBiblioteca, "top:20.0px;left:53.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("90.0%");
		label_1.setHeight("-1px");
		label_1.setValue("Historial de Prèstamos de Libros");
		mainLayout.addComponent(label_1, "top:60.0px;left:459.0px;");
		
		// tablaHistorial
		tablaHistorial = new Table();
		tablaHistorial.setImmediate(false);
		tablaHistorial.setWidth("100.0%");
		tablaHistorial.setHeight("-1px");
		mainLayout.addComponent(tablaHistorial, "top:100.0px;right:59.0px;left:260.0px;");
		
		return mainLayout;
	}

}
