package biblioteca.modulovisitas;

import java.text.SimpleDateFormat;
import java.util.Calendar;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.FieldEvents.FocusEvent;
import com.vaadin.event.FieldEvents.FocusListener;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

public class formularioEditarSolicitud extends CustomComponent implements View
{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private TextField inputFechaEmision;

	@AutoGenerated
	private Label labelFechaSolicitud;

	@AutoGenerated
	private CheckBox checkBoxRECHAZAR;

	@AutoGenerated
	private CheckBox checkBoxACEPTAR;

	@AutoGenerated
	private TextField inputSignatura;

	@AutoGenerated
	private Label labelSolicitud;

	@AutoGenerated
	private Label labelSignatura;

	@AutoGenerated
	private Label labelFechaEntrega;

	@AutoGenerated
	private TextField inputTelefono;

	@AutoGenerated
	private Label labelTelefono;

	@AutoGenerated
	private Button botonGuardar;

	@AutoGenerated
	private Label labelFechaHora;

	@AutoGenerated
	private Label labelVolumen;

	@AutoGenerated
	private TextField inputVolumen;

	@AutoGenerated
	private TextField inputTitulo;

	@AutoGenerated
	private Label labelTituloDoc;

	@AutoGenerated
	private TextField inputAutor;

	@AutoGenerated
	private TextField inputNumero;

	@AutoGenerated
	private Label labelNumero;

	@AutoGenerated
	private TextField inputCedula;

	@AutoGenerated
	private Label labelCedula;

	@AutoGenerated
	private TextField inputApellidos;

	@AutoGenerated
	private Label labelAutor;

	@AutoGenerated
	private Label labelApellidos;

	@AutoGenerated
	private Label labelNombre;

	@AutoGenerated
	private TextField inputNombre;

	@AutoGenerated
	private Label labelTitulo;

	public static final long serialVersionUID = 1202;
	
	private String timeStamp;

	private final DBConnector dbc;
	
	private String IDConsulta;
	
	public static final String EDITVIEW = "edit";
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public formularioEditarSolicitud(String idConsulta, String fechaEmision, String nombre, String apellidos,
	String cedula, String carne, String email, String telefono, String institucion, String tipoUsuario, String tema,
	String tipoConsulta, String observaciones, String basesDatos) 
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		dbc = new DBConnector("localhost","Mutaclotos","we105769");

		timeStamp = new SimpleDateFormat("dd/MM/YYYY HH:mm").format(Calendar.getInstance().getTime());
		labelFechaHora.setValue(timeStamp);
		
		IDConsulta = idConsulta;
		
		//FocusListener para verificar validez de campo modificado
		FocusListener fl = new FocusListener(){
			@Override
			public void focus(FocusEvent event) {
				//inputFechaEntrega.isValid();
			}
		};
		
		
		//inputFechaEntrega.addFocusListener(fl);
		//botonGuardar.addFocusListener(fl);
		
		//Se insertan los valores de la fila de la tabla de consultas en su campo respectivo
		inputNombre.setValue(nombre);
		inputFechaEmision.setValue(fechaEmision);
		inputApellidos.setValue(apellidos);
		inputCedula.setValue(cedula);
		inputTelefono.setValue(telefono);
		
		
		inputFechaEmision.setEnabled(false);
		inputNombre.setEnabled(false);
		inputApellidos.setEnabled(false);
		inputCedula.setEnabled(false);
		inputTelefono.setEnabled(false);
		System.out.println("ID: " + IDConsulta);
		
		botonGuardar.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
			{
				
				String fechaEntrega;
				String tipoConsulta;
				String tema;
				String observaciones;
				
				
				if(true)
				{
					
					try{
						if(checkBoxACEPTAR.getValue())
						{
							fechaEntrega = (new SimpleDateFormat("YYYY-MM-dd HH:mm").format(Calendar.getInstance().getTime()));
							//dbc.update("Consulta","tema='"+tema+"', fechaEntrega='"+fechaEntrega+"', observaciones='"+observaciones+"', tipo='"+tipoConsulta+"'","id='"+IDConsulta+"'");
							
						}
						else
						{
							//dbc.update("Consulta","tema='"+tema+"', observaciones='"+observaciones+"', tipo='"+tipoConsulta+"'","id='"+IDConsulta+"'");
							
						}
						
					}catch(Exception sqe){
					}
					
					System.out.println("Fila modificada.");
					UI.getCurrent().setContent(new formularioConsultaNoCompletada());
				}
			}
		});
	}
	
	@Override
    public void enter(ViewChangeEvent event) {
        Notification.show("Formulario de editar consulta.");
    }
	

	private String[] setSelectedDataBases(String basesDatos)
	{
		String[] bases = basesDatos.split(",");
		
		return bases;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("639px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("639px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("EDITAR SOLICITUD");
		mainLayout.addComponent(labelTitulo, "top:0.0px;left:290.0px;");
		
		// inputNombre
		inputNombre = new TextField();
		inputNombre.setImmediate(false);
		inputNombre.setWidth("-1px");
		inputNombre.setHeight("-1px");
		mainLayout.addComponent(inputNombre, "top:116.0px;left:120.0px;");
		
		// labelNombre
		labelNombre = new Label();
		labelNombre.setImmediate(false);
		labelNombre.setWidth("-1px");
		labelNombre.setHeight("-1px");
		labelNombre.setValue("Nombre:");
		mainLayout.addComponent(labelNombre, "top:120.0px;left:34.0px;");
		
		// labelApellidos
		labelApellidos = new Label();
		labelApellidos.setImmediate(false);
		labelApellidos.setWidth("-1px");
		labelApellidos.setHeight("-1px");
		labelApellidos.setValue("Apellidos:");
		mainLayout.addComponent(labelApellidos, "top:120.0px;left:330.0px;");
		
		// labelAutor
		labelAutor = new Label();
		labelAutor.setImmediate(false);
		labelAutor.setWidth("-1px");
		labelAutor.setHeight("-1px");
		labelAutor.setValue("Autor:");
		mainLayout.addComponent(labelAutor, "top:242.0px;left:330.0px;");
		
		// inputApellidos
		inputApellidos = new TextField();
		inputApellidos.setImmediate(false);
		inputApellidos.setWidth("-1px");
		inputApellidos.setHeight("-1px");
		mainLayout.addComponent(inputApellidos, "top:116.0px;left:419.0px;");
		
		// labelCedula
		labelCedula = new Label();
		labelCedula.setImmediate(false);
		labelCedula.setWidth("-1px");
		labelCedula.setHeight("-1px");
		labelCedula.setValue("Cédula:");
		mainLayout.addComponent(labelCedula, "top:60.0px;left:39.0px;");
		
		// inputCedula
		inputCedula = new TextField();
		inputCedula.setImmediate(false);
		inputCedula.setWidth("-1px");
		inputCedula.setHeight("-1px");
		mainLayout.addComponent(inputCedula, "top:60.0px;left:120.0px;");
		
		// labelNumero
		labelNumero = new Label();
		labelNumero.setImmediate(false);
		labelNumero.setWidth("-1px");
		labelNumero.setHeight("-1px");
		labelNumero.setValue("Número:");
		mainLayout.addComponent(labelNumero, "top:60.0px;left:344.0px;");
		
		// inputNumero
		inputNumero = new TextField();
		inputNumero.setImmediate(false);
		inputNumero.setWidth("-1px");
		inputNumero.setHeight("-1px");
		mainLayout.addComponent(inputNumero, "top:60.0px;left:419.0px;");
		
		// inputAutor
		inputAutor = new TextField();
		inputAutor.setImmediate(false);
		inputAutor.setWidth("-1px");
		inputAutor.setHeight("-1px");
		mainLayout.addComponent(inputAutor, "top:236.0px;left:420.0px;");
		
		// labelTituloDoc
		labelTituloDoc = new Label();
		labelTituloDoc.setImmediate(false);
		labelTituloDoc.setWidth("-1px");
		labelTituloDoc.setHeight("-1px");
		labelTituloDoc.setValue("Título:");
		mainLayout.addComponent(labelTituloDoc, "top:180.0px;left:323.0px;");
		
		// inputTitulo
		inputTitulo = new TextField();
		inputTitulo.setImmediate(false);
		inputTitulo.setWidth("-1px");
		inputTitulo.setHeight("-1px");
		mainLayout.addComponent(inputTitulo, "top:176.0px;left:419.0px;");
		
		// inputVolumen
		inputVolumen = new TextField();
		inputVolumen.setImmediate(false);
		inputVolumen.setWidth("-1px");
		inputVolumen.setHeight("-1px");
		mainLayout.addComponent(inputVolumen, "top:176.0px;left:120.0px;");
		
		// labelVolumen
		labelVolumen = new Label();
		labelVolumen.setImmediate(false);
		labelVolumen.setWidth("-1px");
		labelVolumen.setHeight("-1px");
		labelVolumen.setValue("Volúmen:");
		mainLayout.addComponent(labelVolumen, "top:180.0px;left:43.0px;");
		
		// labelFechaHora
		labelFechaHora = new Label();
		labelFechaHora.setImmediate(false);
		labelFechaHora.setWidth("-1px");
		labelFechaHora.setHeight("-1px");
		labelFechaHora.setValue("1/6/2016  14:21");
		mainLayout.addComponent(labelFechaHora, "top:20.0px;left:480.0px;");
		
		// botonGuardar
		botonGuardar = new Button();
		botonGuardar.setCaption("EDITAR CONSULTA");
		botonGuardar.setImmediate(true);
		botonGuardar.setWidth("240px");
		botonGuardar.setHeight("40px");
		mainLayout.addComponent(botonGuardar, "top:587.0px;left:240.0px;");
		
		// labelTelefono
		labelTelefono = new Label();
		labelTelefono.setImmediate(false);
		labelTelefono.setWidth("-1px");
		labelTelefono.setHeight("-1px");
		labelTelefono.setValue("Teléfono:");
		mainLayout.addComponent(labelTelefono, "top:437.0px;left:0.0px;");
		
		// inputTelefono
		inputTelefono = new TextField();
		inputTelefono.setImmediate(false);
		inputTelefono.setWidth("140px");
		inputTelefono.setHeight("-1px");
		mainLayout.addComponent(inputTelefono, "top:437.0px;left:120.0px;");
		
		// labelFechaEntrega
		labelFechaEntrega = new Label();
		labelFechaEntrega.setImmediate(false);
		labelFechaEntrega.setWidth("-1px");
		labelFechaEntrega.setHeight("-1px");
		labelFechaEntrega.setValue("(la consulta ya no podrá ser editada)");
		mainLayout.addComponent(labelFechaEntrega, "top:541.0px;left:46.0px;");
		
		// labelSignatura
		labelSignatura = new Label();
		labelSignatura.setImmediate(false);
		labelSignatura.setWidth("-1px");
		labelSignatura.setHeight("-1px");
		labelSignatura.setValue("Signatura:");
		mainLayout.addComponent(labelSignatura, "top:300.0px;left:46.0px;");
		
		// labelSolicitud
		labelSolicitud = new Label();
		labelSolicitud.setImmediate(false);
		labelSolicitud.setWidth("-1px");
		labelSolicitud.setHeight("-1px");
		labelSolicitud.setValue("Solicitud de préstamo:");
		mainLayout.addComponent(labelSolicitud, "top:342.0px;left:265.0px;");
		
		// inputSignatura
		inputSignatura = new TextField();
		inputSignatura.setImmediate(false);
		inputSignatura.setWidth("140px");
		inputSignatura.setHeight("-1px");
		mainLayout.addComponent(inputSignatura, "top:300.0px;left:120.0px;");
		
		// checkBoxACEPTAR
		checkBoxACEPTAR = new CheckBox();
		checkBoxACEPTAR.setCaption("ACEPTAR");
		checkBoxACEPTAR.setImmediate(false);
		checkBoxACEPTAR.setWidth("-1px");
		checkBoxACEPTAR.setHeight("-1px");
		mainLayout.addComponent(checkBoxACEPTAR, "top:376.0px;left:500.0px;");
		
		// checkBoxRECHAZAR
		checkBoxRECHAZAR = new CheckBox();
		checkBoxRECHAZAR.setCaption("RECHAZAR");
		checkBoxRECHAZAR.setImmediate(false);
		checkBoxRECHAZAR.setWidth("-1px");
		checkBoxRECHAZAR.setHeight("-1px");
		mainLayout.addComponent(checkBoxRECHAZAR, "top:376.0px;left:600.0px;");
		
		// labelFechaSolicitud
		labelFechaSolicitud = new Label();
		labelFechaSolicitud.setImmediate(false);
		labelFechaSolicitud.setWidth("-1px");
		labelFechaSolicitud.setHeight("-1px");
		labelFechaSolicitud.setValue("Fecha solicitud:");
		mainLayout.addComponent(labelFechaSolicitud, "top:22.0px;left:0.0px;");
		
		// inputFechaEmision
		inputFechaEmision = new TextField();
		inputFechaEmision.setImmediate(false);
		inputFechaEmision.setWidth("-1px");
		inputFechaEmision.setHeight("-1px");
		mainLayout.addComponent(inputFechaEmision, "top:20.0px;left:120.0px;");
		
		return mainLayout;
	}

}
