package biblioteca.modulovisitas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class formularioHistorialPrestamos extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Table tablaHistorial;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Label labelBiblioteca;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private final DBConnector dbc;
	
	private MyUI ui;
	
	public formularioHistorialPrestamos() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		dbc = new DBConnector("localhost","moises","315600");
		ui = new MyUI();
		

		// TODO add user code here
		tablaHistorial.addContainerProperty("   fecha  ", String.class, null);
		tablaHistorial.addContainerProperty("nombre de libro", String.class, null);
		tablaHistorial.addContainerProperty("           ", Button.class, null);
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelBiblioteca
		labelBiblioteca = new Label();
		labelBiblioteca.setImmediate(false);
		labelBiblioteca.setWidth("-1px");
		labelBiblioteca.setHeight("-1px");
		labelBiblioteca.setValue("Biblioteca Francisco Echeverria Garcìa");
		mainLayout.addComponent(labelBiblioteca, "top:20.0px;left:53.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Historial de Prèstamos");
		mainLayout.addComponent(label_1, "top:60.0px;left:420.0px;");
		
		// tablaHistorial
		tablaHistorial = new Table();
		tablaHistorial.setImmediate(false);
		tablaHistorial.setWidth("443px");
		tablaHistorial.setHeight("-1px");
		mainLayout.addComponent(tablaHistorial, "top:100.0px;left:257.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:60.0px;left:760.0px;");
		
		return mainLayout;
	}

}
