package biblioteca.modulovisitas;

import java.sql.ResultSet;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.Filterable;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.data.util.filter.SimpleStringFilter;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

public class formularioSolicitudesPendientes extends CustomComponent implements View
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private TextField inputBusqueda;

	@AutoGenerated
	private ComboBox inputTipoBusqueda;

	@AutoGenerated
	private Table tablaSolicitudes;

	@AutoGenerated
	private Button button_editar;

	@AutoGenerated
	private Button button_buscar;

	@AutoGenerated
	private Label labelTitulo;
	
	Navigator navigator;
	
	public static final String MAINVIEW = "main";

	public static final long serialVersionUID = 1202;
	
	private String timeStamp;

	private final DBConnector dbc;
	
	private MyUI ui;
	
	public formularioSolicitudesPendientes()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		inputTipoBusqueda.setNullSelectionAllowed(false);
		
		dbc = new DBConnector("localhost","Mutaclotos","we105769");
		inputBusqueda.focus();
		ui = new MyUI();
		
		ClickListener click = new ClickListener(){
			SimpleStringFilter filter = null;
			Filterable filterable = null;
			@Override
			public void buttonClick(ClickEvent event) 
			{
				if(inputTipoBusqueda.getValue().toString().equals("Signatura"))
				{
					tablaSolicitudes.setVisibleColumns("Signatura", "Título", "Autor", "Fecha de solicitud", "Solicitante");
					
					filterable = (Container.Filterable) tablaSolicitudes.getContainerDataSource();
					
					//Remover el filtro anterior
					if(filter != null)
					{
						filterable.removeContainerFilter(filter);
					}
					//Nuevo filtro es creado para la columna "Nombre"
					filter = new SimpleStringFilter("Signatura", inputBusqueda.getValue(),true,false);
					filterable.addContainerFilter(filter);
				}
				else if(inputTipoBusqueda.getValue().toString().equals("Título"))
				{
					tablaSolicitudes.setVisibleColumns("Título", "Signatura",  "Autor", "Fecha de solicitud", "Solicitante");
					
					filterable = (Container.Filterable) tablaSolicitudes.getContainerDataSource();
					
					//Remover el filtro anterior
					if(filter != null)
					{
						filterable.removeContainerFilter(filter);
					}
					//Nuevo filtro es creado para la columna "Tema"
					filter = new SimpleStringFilter("Título", inputBusqueda.getValue(),true,false);
					filterable.addContainerFilter(filter);
				}
				else if(inputTipoBusqueda.getValue().toString().equals("Solicitante"))
				{
					tablaSolicitudes.setVisibleColumns("Solicitante", "Fecha de solicitud", "Signatura", "Título", "Autor" );
					
					filterable = (Container.Filterable) tablaSolicitudes.getContainerDataSource();
					
					//Remover el filtro anterior
					if(filter != null)
					{
						filterable.removeContainerFilter(filter);
					}
					//Nuevo filtro es creado para la columna "Fecha emisión"
					filter = new SimpleStringFilter("Solicitante", inputBusqueda.getValue(),true,false);
					filterable.addContainerFilter(filter);
				}
				else if(inputTipoBusqueda.getValue().toString().equals("Fecha de solicitud"))
				{
					tablaSolicitudes.setVisibleColumns("Fecha de solicitud", "Signatura", "Título", "Autor", "Solicitante");
					
					filterable = (Container.Filterable) tablaSolicitudes.getContainerDataSource();
					
					//Remover el filtro anterior
					if(filter != null)
					{
						filterable.removeContainerFilter(filter);
					}
					//Nuevo filtro es creado para la columna "Fecha emisión"
					filter = new SimpleStringFilter("Fecha de solicitud", inputBusqueda.getValue(),true,false);
					filterable.addContainerFilter(filter);
				}
				
			}
		};
		
		this.button_buscar.addClickListener(click);
		
		inputTipoBusqueda.setContainerDataSource(Contenedor.obtenerContenedorTipoBusquedaSolicitud("tipoBusquedaSolicitud"));
		
		inputTipoBusqueda.select("Signatura");
		
		
		int i = 0;
		
		tablaSolicitudes.addContainerProperty("ID", String.class, null);
		tablaSolicitudes.addContainerProperty("Signatura", String.class, null);
		tablaSolicitudes.addContainerProperty("Título", String.class, null);
		tablaSolicitudes.addContainerProperty("Autor", String.class, null);
		tablaSolicitudes.addContainerProperty("Solicitante", String.class, null);
		tablaSolicitudes.addContainerProperty("Fecha de solicitud", String.class, null);
		tablaSolicitudes.addContainerProperty("Estado de solicitud", String.class, null);
		
		tablaSolicitudes.setSelectable(true);
		tablaSolicitudes.setImmediate(true);
		tablaSolicitudes.setColumnCollapsingAllowed(true);
		
		//TODO: modify query
		ResultSet rs = dbc.query("SELECT c.id, u.nombre, u.apellidos, u.cedula, u.carne, u.email, t.numero, u.institucion, u.tipo as tipoUsuario, "
				+ "c.tema, c.tipo, c.fechaEmision, c.observaciones, IFNULL((SELECT GROUP_CONCAT(b.nombre) "
				+ "FROM ConsultaBase cb, BasesDatos b "
				+ "WHERE cb.Consulta = c.id "
				+ "AND b.id = cb.basedatos), 'N/A') AS basesDatos "
				+ "FROM Consulta c, Usuario u, Telefono t "
				+ "WHERE c.fechaEntrega IS NULL "
				+ "AND c.usuario = u.cedula "
				+ "AND t.cedula = u.cedula "
				+ "GROUP BY c.id");
		try{
			
			while(rs.next())
			{
				Integer itemId = new Integer(i);
				String solicitudID = rs.getString("id"); 
				String signatura = rs.getString("signatura");
				String titulo = rs.getString("titulo");
				String autor = rs.getString("autor");
				String usuario = rs.getString("usuario");
				String fecha = rs.getString("fechaSolicitud");
				String aprobado = rs.getString("aprobado");
				
				tablaSolicitudes.addItem(new Object[]{solicitudID,signatura,titulo,autor,usuario,fecha,aprobado}, itemId);
				i++;
			}
		}catch(Exception sqe){
		}
		
		tablaSolicitudes.setVisibleColumns("Signatura", "Título", "Autor", "Solicitante", "Fecha de solicitud", "Estado de solicitud");
		
		
		ClickListener clickEditarSolicitud = new ClickListener(){
			
			@Override
			public void buttonClick(ClickEvent event) 
			{
				//IndexedContainer ic = new IndexedContainer();
				Object rowId = tablaSolicitudes.getValue(); 
				if(rowId != null)
				{
					//System.out.println(rowId.toString());
					String idSolicitud = (String)tablaSolicitudes.getContainerProperty(rowId,"ID").getValue();
					String signatura = (String)tablaSolicitudes.getContainerProperty(rowId,"Signatura").getValue();
					String titulo = (String)tablaSolicitudes.getContainerProperty(rowId,"Título").getValue();
					String autor = (String)tablaSolicitudes.getContainerProperty(rowId,"Autor").getValue();
					String usuario = (String)tablaSolicitudes.getContainerProperty(rowId,"Solicitante").getValue();
					String fecha = (String)tablaSolicitudes.getContainerProperty(rowId,"Fecha de solicitud").getValue();
					String aprobado = (String)tablaSolicitudes.getContainerProperty(rowId,"Estado de solicitud").getValue();
					
					
					//UI.getCurrent().setContent(new formularioEditarSolicitud());
					
				}
				else
				{
					System.out.println("Una fila de la tabla debe ser seleccionada para editar la consulta.");
				}
			}
		};
		
		this.button_editar.addClickListener(clickEditarSolicitud);
	}
	
	@Override
    public void enter(ViewChangeEvent event) {
        Notification.show("Formulario de consultas no completadas");
    }
	
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("440px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("440px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("SOLICITUDES PENDIENTES");
		mainLayout.addComponent(labelTitulo, "top:2.0px;left:651.0px;");
		
		// button_buscar
		button_buscar = new Button();
		button_buscar.setCaption("Buscar");
		button_buscar.setImmediate(true);
		button_buscar.setWidth("100px");
		button_buscar.setHeight("40px");
		mainLayout.addComponent(button_buscar, "top:40.0px;left:680.0px;");
		
		
		// button_editar
		button_editar = new Button();
		button_editar.setCaption("EDITAR SOLICITUD");
		button_editar.setImmediate(true);
		button_editar.setWidth("180px");
		button_editar.setHeight("40px");
		mainLayout.addComponent(button_editar, "top:395.0px;left:280.0px;");
		
		
		// tablaSolicitudes
		tablaSolicitudes = new Table();
		tablaSolicitudes.setImmediate(true);
		tablaSolicitudes.setWidth("90.0%");
		tablaSolicitudes.setHeight("280px");
		mainLayout.addComponent(tablaSolicitudes, "top:100.0px;left:40.0px;");
		
		// inputTipoBusqueda
		inputTipoBusqueda = new ComboBox();
		inputTipoBusqueda.setCaption("Tipo de búsqueda");
		inputTipoBusqueda.setImmediate(false);
		inputTipoBusqueda.setWidth("240px");
		inputTipoBusqueda.setHeight("-1px");
		mainLayout.addComponent(inputTipoBusqueda, "top:40.0px;left:40.0px;");
		
		// inputBusqueda
		inputBusqueda = new TextField();
		inputBusqueda.setImmediate(false);
		inputBusqueda.setWidth("320px");
		inputBusqueda.setHeight("-1px");
		inputBusqueda.setInputPrompt("Buscar...");
		mainLayout.addComponent(inputBusqueda, "top:40.0px;left:320.0px;");
		
		return mainLayout;
	}
}
