package biblioteca.modulovisitas;

import java.sql.ResultSet;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Container.Filterable;
import com.vaadin.data.util.filter.SimpleStringFilter;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;

public class formularioDeslogeo extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button buttonHistorial;
	@AutoGenerated
	private Button buttonNuevoPrestamo;
	@AutoGenerated
	private ComboBox inputTipoBusqueda;
	@AutoGenerated
	private Button buttonDeslogear;
	@AutoGenerated
	private TextField textBusqueda;
	@AutoGenerated
	private Label labelTitulo;
	@AutoGenerated
	private Table tablaUsuario;
	@AutoGenerated
	private Label etiquetaNombreBiblio;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */

	private final DBConnector dbc;
	

	
	private MyUI ui;

	public formularioDeslogeo()  {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		dbc = new DBConnector(MyUI.address,MyUI.user,MyUI.password);
		ui = new MyUI();
		

		buttonDeslogear.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
		
			{
				
				MyUI.tabsheet.replaceComponent(MyUI.tabsheet.getSelectedTab(), new formularioNuevoPrestamo());
			}
	 	});
		
		
		
		
		
		inputTipoBusqueda.setContainerDataSource(Contenedor.obtenerContenedorTipoBusquedaPrestamoActual("tipoBusquedaPrestamoActual"));
		
		inputTipoBusqueda.select("Documento");
		
		tablaUsuario.addContainerProperty("Nombre Usuario", String.class, null);
		tablaUsuario.addContainerProperty("Contraseña", String.class, null);
		int i=0;///////////////////////////////////////////////////////////////////////////////////////////////////


		
		
		ResultSet rs = dbc.query("SELECT u.nombre, u.cedula  from Usuario u where p.usuario=u.cedula and u.cedula ="+ MyUI.user+" ;");//añadir condicion de la cedula del usuario actual"
		
		try{	
		//TODO: datasource de resultSet, tableQuery	
			while(rs.next())
			{
				Integer itemId = new Integer(i);
				
				String nombre = rs.getString("nombre"); 
				String cedula = rs.getString("cedula");


				tablaUsuario.addItem(new Object[]{nombre,cedula}, itemId);
				
				i++;
				//System.out.println(nombreDocu);
				//System.out.println(fechaRetiro);
			}
					
		
		}catch(Exception sqe){
			//System.out.println("faillllll");
		}
		

		tablaUsuario.setPageLength(tablaUsuario.size());
		tablaUsuario.setSelectable(true);
		tablaUsuario.setImmediate(true);
		tablaUsuario.setColumnCollapsingAllowed(true);
		
		
		// TODO add user code here
		
		buttonNuevoPrestamo.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
			{
				MyUI.tabsheet.replaceComponent(MyUI.tabsheet.getSelectedTab(), new formularioNuevoPrestamo());
			}
	 	});
		
		buttonHistorial.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
			{
				MyUI.tabsheet.replaceComponent(MyUI.tabsheet.getSelectedTab(), new formularioHistorialPrestamos());
			}
	 	});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("505px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("505px");
		
		// etiquetaNombreBiblio
		etiquetaNombreBiblio = new Label();
		etiquetaNombreBiblio.setImmediate(false);
		etiquetaNombreBiblio.setWidth("280px");
		etiquetaNombreBiblio.setHeight("40px");
		etiquetaNombreBiblio.setValue("Bibioteca Francisco Echeverria Garcìa");
		mainLayout.addComponent(etiquetaNombreBiblio, "top:20.0px;left:100.0px;");
		
		// tablaUsuario
		tablaUsuario = new Table();
		tablaUsuario.setImmediate(false);
		tablaUsuario.setWidth("100.0%");
		tablaUsuario.setHeight("40px");
		mainLayout.addComponent(tablaUsuario, "top:140.0px;right:62.0px;left:260.0px;");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("100.0%");
		labelTitulo.setHeight("18px");
		labelTitulo.setValue("Teminar sesion?");
		mainLayout.addComponent(labelTitulo, "top:62.0px;right:209.0px;left:440.0px;");
		

		
		// buttonDeslogear
		buttonDeslogear = new Button();
		buttonDeslogear.setCaption("Deslogear");
		buttonDeslogear.setImmediate(true);
		buttonDeslogear.setWidth("-1px");
		buttonDeslogear.setHeight("-1px");
		mainLayout.addComponent(buttonDeslogear, "top:234.0px;left:573.0px;");
		

		
		// buttonNuevoPrestamo
		buttonNuevoPrestamo = new Button();
		buttonNuevoPrestamo.setCaption("NUEVO PRESTAMO");
		buttonNuevoPrestamo.setImmediate(true);
		buttonNuevoPrestamo.setWidth("160px");
		buttonNuevoPrestamo.setHeight("-1px");
		mainLayout.addComponent(buttonNuevoPrestamo, "top:460.0px;left:236.0px;");
		
		// buttonHistorial
		buttonHistorial = new Button();
		buttonHistorial.setCaption("HISTORIAL DE PRESTAMOS");
		buttonHistorial.setImmediate(true);
		buttonHistorial.setWidth("240px");
		buttonHistorial.setHeight("-1px");
		mainLayout.addComponent(buttonHistorial, "top:460.0px;left:496.0px;");
		
		return mainLayout;
	}

}