package biblioteca.modulovisitas;

import java.sql.ResultSet;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

public class formularioDeslogeo extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label labelDeNombre;
	@AutoGenerated
	private Button buttonDeslogear;
	@AutoGenerated
	private Label labelTitulo;
	@AutoGenerated
	private Label etiquetaNombreBiblio;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */

	private final DBConnector dbc;
	

	
	private MyUI ui;
	
	MyUI m;
	
	
	String usuario;
	
	
	public formularioDeslogeo(MyUI main ,String user)  {
		this.m = main;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		dbc = new DBConnector(MyUI.address,MyUI.user,MyUI.password);
		ui = new MyUI();
		
		this.usuario = user;
		

		buttonDeslogear.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
		
			{
				
				MyUI.getCurrent().setContent(new formularioLoginNormal(m));
				
			}
	 	});
		
		
		
		
		
		
		int i=0;///////////////////////////////////////////////////////////////////////////////////////////////////


		
		
		ResultSet rs = dbc.query("SELECT u.nombre, u.apellidos  from Usuario u where  u.cedula ="+user +";");//añadir condicion de la cedula del usuario actual"
		
		try{	
		//TODO: datasource de resultSet, tableQuery	
			while(rs.next())
			{
				Integer itemId = new Integer(i);
				
				String nombre = rs.getString("nombre"); 
				String apellidos = rs.getString("apellidos");

				labelDeNombre.setCaption(nombre +" " +apellidos);
				//tablaUsuario.addItem(new Object[]{nombre}, itemId);
				
				i++;
				System.out.println(nombre);
				System.out.println(apellidos);
			}
					
		
		}catch(Exception sqe){
			//System.out.println("faillllll");
		}
	
	}
		
		// TODO add user code here
		


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("505px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("505px");
		
		// etiquetaNombreBiblio
		etiquetaNombreBiblio = new Label();
		etiquetaNombreBiblio.setImmediate(false);
		etiquetaNombreBiblio.setWidth("280px");
		etiquetaNombreBiblio.setHeight("40px");
		etiquetaNombreBiblio.setValue("Bibioteca Francisco Echeverria Garcìa");
		mainLayout.addComponent(etiquetaNombreBiblio, "top:20.0px;left:100.0px;");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("100.0%");
		labelTitulo.setHeight("18px");
		labelTitulo.setValue("Teminar sesion?");
		mainLayout.addComponent(labelTitulo, "top:62.0px;right:209.0px;left:440.0px;");
		
		// buttonDeslogear
		buttonDeslogear = new Button();
		buttonDeslogear.setCaption("Deslogear");
		buttonDeslogear.setImmediate(true);
		buttonDeslogear.setWidth("-1px");
		buttonDeslogear.setHeight("-1px");
		mainLayout.addComponent(buttonDeslogear, "top:234.0px;left:573.0px;");
		
		// labelDeNombre
		labelDeNombre = new Label();
		labelDeNombre.setImmediate(false);
		labelDeNombre.setWidth("240px");
		labelDeNombre.setHeight("-1px");
		labelDeNombre.setValue("-");
		mainLayout.addComponent(labelDeNombre, "top:160.0px;left:380.0px;");
		
		return mainLayout;
	}

}