package biblioteca.modulovisitas;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.FieldEvents.FocusEvent;
import com.vaadin.event.FieldEvents.FocusListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

import biblioteca.modulovisitas.validadores.IsApellido;
import biblioteca.modulovisitas.validadores.IsCarne;
import biblioteca.modulovisitas.validadores.IsCedula;
import biblioteca.modulovisitas.validadores.IsEmail;
import biblioteca.modulovisitas.validadores.IsFecha;
import biblioteca.modulovisitas.validadores.IsInstitucion;
import biblioteca.modulovisitas.validadores.IsNombre;
import biblioteca.modulovisitas.validadores.IsTelefono;

public class formularioNuevoPrestamo extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private TextField inputVolumen;

	@AutoGenerated
	private Label labelVolumen;

	@AutoGenerated
	private TextField inputAnio;

	@AutoGenerated
	private Label labelAnio;

	@AutoGenerated
	private Label labelFecha;

	@AutoGenerated
	private Button botonGuardar;

	@AutoGenerated
	private Label labelFechaHora;

	@AutoGenerated
	private Label label_1;

	@AutoGenerated
	private TextField inputTitulo;

	@AutoGenerated
	private TextField inputInstitucion;

	@AutoGenerated
	private Label labelInstitucion;

	@AutoGenerated
	private ComboBox inputTipoDocumento;

	@AutoGenerated
	private TextField inputNumero;

	@AutoGenerated
	private TextField inputSignatura;

	@AutoGenerated
	private Label labelSignatura;

	@AutoGenerated
	private Label labelNumero;

	@AutoGenerated
	private Label labelAutor;

	@AutoGenerated
	private TextField inputAutor;

	@AutoGenerated
	private Label labelTitulo;

	public static final long serialVersionUID = 1202;
	
	private String timeStamp;

	private final DBConnector dbc;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public formularioNuevoPrestamo() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		dbc = new DBConnector("localhost","Mutaclotos","we105769");

		timeStamp = new SimpleDateFormat("dd/MM/YYYY HH:mm").format(Calendar.getInstance().getTime());
		labelFechaHora.setValue(timeStamp);
		
	
		FocusListener fl = new FocusListener(){
			@Override
			public void focus(FocusEvent event) {
				inputInstitucion.isValid();
				inputAutor.isValid();
				inputSignatura.isValid();
				inputNumero.isValid();
				inputAnio.isValid();
				inputTitulo.isValid();
			}
		};
		
		inputInstitucion.addFocusListener(fl);
		inputAutor.addFocusListener(fl);
		inputSignatura.addFocusListener(fl);
		inputNumero.addFocusListener(fl);
		inputAnio.addFocusListener(fl);
		inputTitulo.addFocusListener(fl);
		botonGuardar.addFocusListener(fl);
		
		
		inputTipoDocumento.setContainerDataSource(Contenedor.obtenerContenedorTipoDocumento("tipoDocumento"));
		
		
		botonGuardar.addClickListener(new ClickListener(){
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event) {
				
				inputInstitucion.addValidator(new IsInstitucion());
				
				
				String autor;
				String signatura;
				String numero;
				String anio;
				String titulo;
				String institucion;
				String tipoDocumento;
				int idConsulta = 0;
				boolean noError = (inputInstitucion.isValid() && inputAutor.isValid() && inputSignatura.isValid() &&
				inputNumero.isValid() && inputAnio.isValid() && inputTitulo.isValid());
				if(noError){
					autor = inputAutor.getValue();
					signatura = inputSignatura.getValue();
					anio = inputAnio.getValue();
					titulo = inputTitulo.getValue();
					numero = inputNumero.getValue();
					institucion = inputInstitucion.getValue();
					tipoDocumento = inputTipoDocumento.getValue().toString();

					/*ResultSet rs = dbc.query("SELECT 1 FROM Usuario WHERE cedula='"+cedula+"'");
					try{
						if(!rs.next()){//Si no exiten regitros con esta cedula
							System.out.println("Insertando nuevo usuario.");
							dbc.insert("Usuario",cedula,carne,apellidos,nombre,email,institucion,tipoUsuario);
							dbc.insert("Telefono",cedula,telefono);
						}
					}catch(Exception sqe){
					}
					
					dbc.insert("Consulta",null,tema,fechaEmision,fechaEntrega,observaciones,cedula,tipoConsulta);
					ResultSet rs2 = dbc.query("SELECT id FROM consulta ORDER BY id");
					
					try{
						rs2.last();
						idConsulta = rs2.getInt(1);
						System.out.println("Id: " + idConsulta);
					}catch(Exception sqe){
					}*/
					
					
						
					
					inputTitulo.setValue("");
					inputSignatura.setValue("");
					inputAutor.setValue("");
					inputNumero.setValue("");
					inputVolumen.setValue("");
					inputAnio.setValue("");
					inputInstitucion.setValue("");
					
				}
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("623px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("623px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("NUEVA SOLICITUD");
		mainLayout.addComponent(labelTitulo, "top:2.0px;left:291.0px;");
		
		// inputAutor
		inputAutor = new TextField();
		inputAutor.setImmediate(false);
		inputAutor.setWidth("480px");
		inputAutor.setHeight("-1px");
		mainLayout.addComponent(inputAutor, "top:200.0px;left:120.0px;");
		
		// labelAutor
		labelAutor = new Label();
		labelAutor.setImmediate(false);
		labelAutor.setWidth("-1px");
		labelAutor.setHeight("-1px");
		labelAutor.setValue("Autor:");
		mainLayout.addComponent(labelAutor, "top:202.0px;left:48.0px;");
		
		// labelNumero
		labelNumero = new Label();
		labelNumero.setImmediate(false);
		labelNumero.setWidth("-1px");
		labelNumero.setHeight("-1px");
		labelNumero.setValue("Número:");
		mainLayout.addComponent(labelNumero, "top:439.0px;left:34.0px;");
		
		
		// labelSignatura
		labelSignatura = new Label();
		labelSignatura.setImmediate(false);
		labelSignatura.setWidth("-1px");
		labelSignatura.setHeight("-1px");
		labelSignatura.setValue("Signatura:");
		mainLayout.addComponent(labelSignatura, "top:142.0px;left:25.0px;");
		
		// inputSignatura
		inputSignatura = new TextField();
		inputSignatura.setImmediate(false);
		inputSignatura.setWidth("-1px");
		inputSignatura.setHeight("-1px");
		mainLayout.addComponent(inputSignatura, "top:140.0px;left:120.0px;");
		
		
		// inputNumero
		inputNumero = new TextField();
		inputNumero.setImmediate(false);
		inputNumero.setWidth("80px");
		inputNumero.setHeight("-1px");
		mainLayout.addComponent(inputNumero, "top:443.0px;left:120.0px;");
		
		
		// inputTipoDocumento
		inputTipoDocumento = new ComboBox();
		inputTipoDocumento.setCaption("Tipo de documento:");
		inputTipoDocumento.setImmediate(false);
		inputTipoDocumento.setWidth("141px");
		inputTipoDocumento.setHeight("-1px");
		mainLayout.addComponent(inputTipoDocumento, "top:80.0px;left:120.0px;");
		
		
		// labelInstitucion
		labelInstitucion = new Label();
		labelInstitucion.setImmediate(false);
		labelInstitucion.setWidth("-1px");
		labelInstitucion.setHeight("-1px");
		labelInstitucion.setValue("Institución:");
		mainLayout.addComponent(labelInstitucion, "top:329.0px;left:23.0px;");
		
		// inputInstitucion
		inputInstitucion = new TextField();
		inputInstitucion.setImmediate(false);
		inputInstitucion.setWidth("-1px");
		inputInstitucion.setHeight("-1px");
		mainLayout.addComponent(inputInstitucion, "top:318.0px;left:120.0px;");
		
		// inputTitulo
		inputTitulo = new TextField();
		inputTitulo.setImmediate(false);
		inputTitulo.setWidth("480px");
		inputTitulo.setHeight("-1px");
		mainLayout.addComponent(inputTitulo, "top:260.0px;left:120.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Título:");
		mainLayout.addComponent(label_1, "top:262.0px;left:46.0px;");
		
		// labelFechaHora
		labelFechaHora = new Label();
		labelFechaHora.setImmediate(false);
		labelFechaHora.setWidth("-1px");
		labelFechaHora.setHeight("-1px");
		labelFechaHora.setValue("1/6/2016  14:21");
		mainLayout.addComponent(labelFechaHora, "top:42.0px;left:520.0px;");
		
		// botonGuardar
		botonGuardar = new Button();
		botonGuardar.setCaption("Enviar Solicitud");
		botonGuardar.setImmediate(true);
		botonGuardar.setWidth("240px");
		botonGuardar.setHeight("40px");
		mainLayout.addComponent(botonGuardar, "top:587.0px;left:240.0px;");
		
		// labelFecha
		labelFecha = new Label();
		labelFecha.setImmediate(false);
		labelFecha.setWidth("-1px");
		labelFecha.setHeight("100.0%");
		labelFecha.setValue("Fecha:");
		mainLayout.addComponent(labelFecha, "top:40.0px;bottom:-21.0px;left:443.0px;");
		
		// labelAnio
		labelAnio = new Label();
		labelAnio.setImmediate(false);
		labelAnio.setWidth("-1px");
		labelAnio.setHeight("-1px");
		labelAnio.setValue("Año:");
		mainLayout.addComponent(labelAnio, "top:503.0px;left:54.0px;");
		
		// inputAnio
		inputAnio = new TextField();
		inputAnio.setImmediate(false);
		inputAnio.setWidth("60px");
		inputAnio.setHeight("-1px");
		mainLayout.addComponent(inputAnio, "top:503.0px;left:120.0px;");
		
		
		// labelVolumen
		labelVolumen = new Label();
		labelVolumen.setImmediate(false);
		labelVolumen.setWidth("-1px");
		labelVolumen.setHeight("-1px");
		labelVolumen.setValue("Volumen:");
		mainLayout.addComponent(labelVolumen, "top:385.0px;left:29.0px;");
		
		
		// inputVolumen
		inputVolumen = new TextField();
		inputVolumen.setImmediate(false);
		inputVolumen.setWidth("140px");
		inputVolumen.setHeight("-1px");
		mainLayout.addComponent(inputVolumen, "top:383.0px;left:120.0px;");
		
		return mainLayout;
	}

}
