package biblioteca.modulovisitas;

import java.util.Collection;

import com.vaadin.addon.charts.Chart;
import com.vaadin.addon.charts.model.ChartType;
import com.vaadin.addon.charts.model.Configuration;
import com.vaadin.addon.charts.model.ContainerDataSeries;
import com.vaadin.addon.tableexport.ExcelExport;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;


public class graficosVisitas extends CustomComponent {
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private Button boton_excel;

	@AutoGenerated
	private Table table_excel;

	@AutoGenerated
	private Button buttonExportar;

	@AutoGenerated
	private Button button_Dibujar;

	@AutoGenerated
	private Label label_tipo2;

	@AutoGenerated
	private Label label_Fecha;

	@AutoGenerated
	private Label label_tipo;

	@AutoGenerated
	private AbsoluteLayout espacioGrafico;

	@AutoGenerated
	private ComboBox input_por;

	@AutoGenerated
	private ComboBox input_fecha;

	@AutoGenerated
	private ComboBox input_tipo;

	@AutoGenerated
	private Label labelTitulo;

	public static final long serialVersionUID = 12764;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private  DBConnector dbc;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public graficosVisitas() {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		dbc = new DBConnector(MyUI.address,MyUI.user,MyUI.password);
		

		this.input_tipo.setNullSelectionAllowed(false);
		this.input_tipo.setContainerDataSource(Contenedor.obtenerContenedorGraficoTipo());
		
		this.input_por.setNullSelectionAllowed(false);
		this.input_por.setContainerDataSource(Contenedor.obtenerContenedorGraficoPor());
		this.input_fecha.setNullSelectionAllowed(false);
		
		this.button_Dibujar.addClickListener(new ClickListener(){
			@Override
			public void buttonClick(ClickEvent event) {
				dibujarGrafico();
			}
		});
		this.input_tipo.addValueChangeListener(new ValueChangeListener(){
			@Override
			public void valueChange(ValueChangeEvent event) {
				actualizarFecha();
			}
		});
		
		
		boton_excel.addClickListener(new ClickListener()
		{
			private static final long serialVersionUID = 47254532L;
			@Override
			public void buttonClick(ClickEvent event)
			{
				
				try{
					excel();
				}
				catch(Exception e){
					
				}
			}
	 	});
		
	}
  
	private void actualizarFecha(){
		this.input_fecha.setContainerDataSource(Contenedor.obtenerContenedorGraficoVisitaFecha(this.input_tipo.getValue().toString(), dbc));
	}
	
	private void excel(){

		table_excel.setImmediate(true);

		ExcelExport excelExport;

		    excelExport = new ExcelExport(table_excel);

		     excelExport.excludeCollapsedColumns();

		     excelExport.setReportTitle("Numero de Visitas");

		     excelExport.export();

		}
	
	
	
	private void dibujarGrafico(){

		Chart chart = new Chart();

	    final Configuration configuration = chart.getConfiguration();
        configuration.getChart().setType(ChartType.PIE);
        configuration.getTitle().setText("Gráfico registro de Visita");

        ContainerDataSeries container = 
        		new ContainerDataSeries(
        				Contenedor.obtenerContenedorGraficoVisita(this.input_tipo.getValue().toString(),this.input_fecha.getValue().toString(),this.input_por.getValue().toString(),dbc)
        				);
        container.setName("Cantidad");

        container.setYPropertyId("y");
        container.setNamePropertyId("name");
        configuration.setSeries(container);
        chart.drawChart(configuration);
	    espacioGrafico.addComponent(chart);	
	    
	    ///////////
	    
	    int i =0;
        String prueba=container.toString();
        System.out.println("tthis is ittt");
        System.out.println(prueba);
        Container container2 = Contenedor.obtenerContenedorGraficoVisita(this.input_tipo.getValue().toString(),this.input_fecha.getValue().toString(),this.input_por.getValue().toString(),dbc);
        Collection <?> listaIds = container2.getItemIds();
        Object Ids [] =listaIds.toArray();
        int contadorTabla = listaIds.size();
        
        //Table table_excel = new Table("Datos"/*,container2*/ );
        table_excel.setPageLength(container2.size());
        //table_excel.setVisibleColumns("name","y");
        table_excel.addContainerProperty("Nombre", String.class, null);
        table_excel.addContainerProperty("Visitas", String.class, null);
        table_excel.setImmediate(true);

    	String separador;
        int j=0;
        while (j<contadorTabla){
        	
        	separador =container2.getItem(Ids[j]).toString();
        	String b [] = separador.split("\\s+(?=[0-9])");
        	System.out.println(b[0]+"@"+b[1]);
        	table_excel.addItem(new Object[]{b[0],b[1]},j);
        	j++;
        }
        

	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("800px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("800px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("GRAFICO DE VISITAS");
		mainLayout.addComponent(labelTitulo, "top:0.0px;left:256.0px;");
		
		// input_tipo
		input_tipo = new ComboBox();
		input_tipo.setImmediate(false);
		input_tipo.setWidth("125px");
		input_tipo.setHeight("-1px");
		mainLayout.addComponent(input_tipo, "top:38.0px;left:59.0px;");
		
		// input_fecha
		input_fecha = new ComboBox();
		input_fecha.setImmediate(false);
		input_fecha.setWidth("125px");
		input_fecha.setHeight("-1px");
		mainLayout.addComponent(input_fecha, "top:37.0px;left:281.0px;");
		
		// input_por
		input_por = new ComboBox();
		input_por.setImmediate(false);
		input_por.setWidth("125px");
		input_por.setHeight("-1px");
		mainLayout.addComponent(input_por, "top:38.0px;right:43.0px;left:500.0px;");
		
		// espacioGrafico
		espacioGrafico = new AbsoluteLayout();
		espacioGrafico.setImmediate(false);
		espacioGrafico.setWidth("420px");
		espacioGrafico.setHeight("500px");
		mainLayout.addComponent(espacioGrafico, "top:140.0px;left:40.0px;");
		
		// label_tipo
		label_tipo = new Label();
		label_tipo.setImmediate(false);
		label_tipo.setWidth("-1px");
		label_tipo.setHeight("-1px");
		label_tipo.setValue("Tipo:");
		mainLayout.addComponent(label_tipo, "top:42.0px;left:20.0px;");
		
		// label_Fecha
		label_Fecha = new Label();
		label_Fecha.setImmediate(false);
		label_Fecha.setWidth("-1px");
		label_Fecha.setHeight("-1px");
		label_Fecha.setValue("Fecha:");
		mainLayout.addComponent(label_Fecha, "top:42.0px;left:220.0px;");
		
		// label_tipo2
		label_tipo2 = new Label();
		label_tipo2.setImmediate(false);
		label_tipo2.setWidth("-1px");
		label_tipo2.setHeight("-1px");
		label_tipo2.setValue("Por:");
		mainLayout.addComponent(label_tipo2, "top:42.0px;left:460.0px;");
		
		// button_Dibujar
		button_Dibujar = new Button();
		button_Dibujar.setCaption("Generar");
		button_Dibujar.setImmediate(true);
		button_Dibujar.setWidth("-1px");
		button_Dibujar.setHeight("-1px");
		mainLayout.addComponent(button_Dibujar, "top:94.0px;left:220.0px;");
		
		// buttonExportar
		buttonExportar = new Button();
		buttonExportar.setCaption("Exportar");
		buttonExportar.setImmediate(true);
		buttonExportar.setWidth("-1px");
		buttonExportar.setHeight("-1px");
		mainLayout.addComponent(buttonExportar, "top:661.0px;left:240.0px;");
		
		// table_excel
		table_excel = new Table();
		table_excel.setImmediate(false);
		table_excel.setWidth("200px");
		table_excel.setHeight("363px");
		mainLayout.addComponent(table_excel, "top:137.0px;left:500.0px;");
		
		// boton_excel
		boton_excel = new Button();
		boton_excel.setCaption("Exportar a Excel");
		boton_excel.setImmediate(true);
		boton_excel.setWidth("-1px");
		boton_excel.setHeight("-1px");
		mainLayout.addComponent(boton_excel, "top:94.0px;left:520.0px;");
		
		return mainLayout;
	}

}
