package biblioteca.modulovisitas;

import com.vaadin.addon.charts.Chart;
import com.vaadin.addon.charts.PointClickEvent;
import com.vaadin.addon.charts.PointClickListener;
import com.vaadin.addon.charts.model.ChartType;
import com.vaadin.addon.charts.model.Configuration;
import com.vaadin.addon.charts.model.Cursor;
import com.vaadin.addon.charts.model.DataLabels;
import com.vaadin.addon.charts.model.DataSeries;
import com.vaadin.addon.charts.model.DataSeriesItem;
import com.vaadin.addon.charts.model.PlotOptionsPie;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;


public class graficosVisitas extends CustomComponent {
	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private Label label_tipo2;

	@AutoGenerated
	private Label label_Fecha;

	@AutoGenerated
	private Label label_tipo;

	@AutoGenerated
	private AbsoluteLayout espacioGrafico;

	@AutoGenerated
	private ComboBox input_por;

	@AutoGenerated
	private ComboBox input_fecha;

	@AutoGenerated
	private ComboBox input_tipo;

	@AutoGenerated
	private Label labelTitulo;

	public static final long serialVersionUID = 1202;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private  DBConnector dbc;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public graficosVisitas() {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		//dbc = new DBConnector("192.168.56.101","root","GESAVA954");
		
		Chart chart = new Chart(ChartType.PIE);

        Configuration conf = chart.getConfiguration();

        conf.setTitle("Browser market shares at a specific website, 2010");

        PlotOptionsPie plotOptions = new PlotOptionsPie();
        plotOptions.setCursor(Cursor.POINTER);
        DataLabels dataLabels = new DataLabels();
        dataLabels.setEnabled(true);
        dataLabels
                .setFormatter("'<b>'+ this.point.name +'</b>: '+ this.percentage +' %'");
        plotOptions.setDataLabels(dataLabels);
        conf.setPlotOptions(plotOptions);

        final DataSeries series = new DataSeries();
        series.add(new DataSeriesItem("Firefox", 45.0));
        series.add(new DataSeriesItem("IE", 26.8));
        DataSeriesItem chrome = new DataSeriesItem("Chrome", 12.8);
        chrome.setSliced(true);
        chrome.setSelected(true);
        series.add(chrome);
        series.add(new DataSeriesItem("Safari", 8.5));
        series.add(new DataSeriesItem("Opera", 6.2));
        series.add(new DataSeriesItem("Others", 0.7));
        conf.setSeries(series);

        chart.addPointClickListener(new PointClickListener() {

            @Override
            public void onClick(PointClickEvent event) {
                Notification.show("Click: "
                        + series.get(event.getPointIndex()).getName());
            }
        });

        chart.drawChart(conf);
        
        
        espacioGrafico.addComponent(chart);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("460px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("460px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("CONTROL VISITAS");
		mainLayout.addComponent(labelTitulo, "top:0.0px;left:256.0px;");
		
		// input_tipo
		input_tipo = new ComboBox();
		input_tipo.setImmediate(false);
		input_tipo.setWidth("125px");
		input_tipo.setHeight("-1px");
		mainLayout.addComponent(input_tipo, "top:38.0px;left:59.0px;");
		
		// input_fecha
		input_fecha = new ComboBox();
		input_fecha.setImmediate(false);
		input_fecha.setWidth("125px");
		input_fecha.setHeight("-1px");
		mainLayout.addComponent(input_fecha, "top:37.0px;left:281.0px;");
		
		// input_por
		input_por = new ComboBox();
		input_por.setImmediate(false);
		input_por.setWidth("125px");
		input_por.setHeight("-1px");
		mainLayout.addComponent(input_por, "top:38.0px;right:43.0px;left:500.0px;");
		
		// espacioGrafico
		espacioGrafico = new AbsoluteLayout();
		espacioGrafico.setImmediate(false);
		espacioGrafico.setWidth("560px");
		espacioGrafico.setHeight("300px");
		mainLayout.addComponent(espacioGrafico, "top:120.0px;left:40.0px;");
		
		// label_tipo
		label_tipo = new Label();
		label_tipo.setImmediate(false);
		label_tipo.setWidth("-1px");
		label_tipo.setHeight("-1px");
		label_tipo.setValue("Tipo");
		mainLayout.addComponent(label_tipo, "top:42.0px;left:20.0px;");
		
		// label_Fecha
		label_Fecha = new Label();
		label_Fecha.setImmediate(false);
		label_Fecha.setWidth("-1px");
		label_Fecha.setHeight("-1px");
		label_Fecha.setValue("Fecha");
		mainLayout.addComponent(label_Fecha, "top:42.0px;left:220.0px;");
		
		// label_tipo2
		label_tipo2 = new Label();
		label_tipo2.setImmediate(false);
		label_tipo2.setWidth("-1px");
		label_tipo2.setHeight("-1px");
		label_tipo2.setValue("Por:");
		mainLayout.addComponent(label_tipo2, "top:42.0px;left:460.0px;");
		
		return mainLayout;
	}

}
